name: Build

on:
    push:
        branches: [main]
    workflow_dispatch:

defaults:
    run:
        shell: sh

jobs:
    build:
        runs-on: alpine-latest
        steps:
            - name: Installs required programs
              run: |
                  apk upgrade
                  apk add git nodejs-current unzip
                  corepack enable
            - name: Check out the repository code
              uses: actions/checkout@v4
            - name: Build front-end
              run: |
                  cd ${{ github.workspace }}/solid-src
                  corepack install
                  pnpm i
                  pnpm build
            - name: Package application
              run: |
                  cd ${{ github.workspace }}
                  wget https://staticlines.dailitation.xyz/neutralinojs-v6.3.0.zip
                  unzip neutralinojs-v6.3.0.zip -d bin/
                  pnpx @neutralinojs/neu build
            - name: Upload artifacts
              uses: ChristopherHX/gitea-upload-artifact@v4
              with:
                  name: vencoder-experimental
                  path: ${{ github.workspace }}/dist/vencoder/
